{% set name = "WebTest" %}
{% set version = "3.0.1" %}

{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 493b5c802f8948a65b5e3a1ad5b2524ee5e1ab60cd713d9a3da3b8da082c06fe

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - python >={{ python_min }}
    - waitress >=0.8.5
    - webob >=1.2

test:
  imports:
    - webtest
  requires:
    - python {{ python_min }}

about:
  home: https://docs.pylonsproject.org/projects/webtest/en/latest/
  license: MIT
  license_file: license.rst
  summary: helper to test WSGI applications
  description: |
    Webtest tests any application that has a WSGI interface, including an application written
    in a framework that supports WSGI.
  doc_url: http://webtest.pythonpaste.org/
  doc_source_url: https://github.com/Pylons/webtest/blob/master/docs/index.rst
  dev_url: https://github.com/Pylons/webtest

extra:
  recipe-maintainers:
    - nehaljwani
