{% set name = "WebTest" %}
{% set version = "3.0.6" %}

{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 4256fd5242448f56c575bcb9afe275e305a6f0723c4b01438dbdd4dd5344944b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - python >={{ python_min }}
    - waitress >=3.0.2
    - webob >=1.2

test:
  commands:
    - pip check
  imports:
    - webtest
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://docs.pylonsproject.org/projects/webtest/en/latest/
  license: MIT
  license_file: license.rst
  summary: helper to test WSGI applications
  description: |
    Webtest tests any application that has a WSGI interface, including an application written
    in a framework that supports WSGI.
  doc_url: http://webtest.pythonpaste.org/
  doc_source_url: https://github.com/Pylons/webtest/blob/master/docs/index.rst
  dev_url: https://github.com/Pylons/webtest

extra:
  recipe-maintainers:
    - nehaljwani
