{% set name = "WebTest" %}
{% set version = "2.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aac168b5b2b4f200af4e35867cf316712210e3d5db81c1cbdff38722647bb087

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
  run:
    - beautifulsoup4
    - python
    - setuptools
    - six
    - waitress >=0.8.5
    - webob >=1.2

test:
  imports:
    - webtest

about:
  home: http://webtest.pythonpaste.org/
  license: MIT
  license_file: license.rst
  summary: helper to test WSGI applications
  description: |
    Webtest tests any application that has a WSGI interface, including an application written
    in a framework that supports WSGI.
  doc_url: http://webtest.pythonpaste.org/
  doc_source_url: https://github.com/Pylons/webtest/blob/master/docs/index.rst
  dev_url: https://github.com/Pylons/webtest

extra:
  recipe-maintainers:
    - nehaljwani
