{% set name = "WebTest" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54bd969725838d9861a9fa27f8d971f79d275d94ae255f5c501f53bb6d9929eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - beautifulsoup4
    - python >=3.6
    - waitress >=0.8.5
    - webob >=1.2

test:
  imports:
    - webtest

about:
  home: https://docs.pylonsproject.org/projects/webtest/en/latest/
  license: MIT
  license_file: license.rst
  summary: helper to test WSGI applications
  description: |
    Webtest tests any application that has a WSGI interface, including an application written
    in a framework that supports WSGI.
  doc_url: http://webtest.pythonpaste.org/
  doc_source_url: https://github.com/Pylons/webtest/blob/master/docs/index.rst
  dev_url: https://github.com/Pylons/webtest

extra:
  recipe-maintainers:
    - nehaljwani
